name: nxs-build-tools
version:
  major: 0
  minor: 1
  patch: 3
builds:
- name: "debian"
  deb:
    dh_make:
    - "--copyright=gpl3"
    - "--single"
    - "--templates=../build-scope/tpls/debian"
    - "--yes"
    - "--createorig"
    dpkg_buildpackage:
    - "-us"
    - "-uc"
- name: "centos"
  rpm:
    cmake:
    - "-DRPM=on"
    - "."
    make:
    - "package"
